channels:
  - conda-forge
dependencies:
  - python==3.10
  - jupyterlab
  - ipywidgets
  - ipykernel
  - jupyterlab-git
  - jupyter
  - matplotlib
  - ffmpeg
  - rclone
  - awscli
  - hdf5tools
  - pytables
  - pytest
  - pip
  - powerlaw
